# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-09 13:32
from __future__ import unicode_literals

import common.utils
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_id', models.CharField(default=common.utils.get_unique_id, max_length=16, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='相册名称')),
                ('is_show', models.BooleanField(default=True, verbose_name='电子班牌是否显示')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '班级相册',
                'verbose_name_plural': '班级相册',
            },
        ),
        migrations.CreateModel(
            name='ClassHonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_honor_id', models.CharField(default=common.utils.get_unique_id, max_length=16, unique=True, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='荣誉主题')),
                ('get_time', models.DateTimeField(verbose_name='荣誉获得时间')),
                ('desc', models.TextField(verbose_name='荣誉描述')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '班级荣誉',
                'verbose_name_plural': '班级荣誉',
            },
        ),
        migrations.CreateModel(
            name='ClassNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(default=common.utils.get_unique_id, max_length=16, unique=True, verbose_name='ID')),
                ('type', models.CharField(choices=[('class', '班级'), ('school', '学校')], default='class', max_length=16, verbose_name='通知类型')),
                ('title', models.CharField(max_length=64, verbose_name='主题')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='上传图片')),
                ('content', models.TextField(verbose_name='内容')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始显示时间')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='设置结束时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
            },
        ),
        migrations.CreateModel(
            name='GalleryImageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(default=common.utils.get_unique_id, max_length=16, unique=True, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='图片')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '相册照片',
                'verbose_name_plural': '相册照片',
            },
        ),
        migrations.CreateModel(
            name='HonorImageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(default=common.utils.get_unique_id, max_length=16, unique=True, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='图片')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '荣誉照片',
                'verbose_name_plural': '荣誉照片',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(default=common.utils.get_unique_id, max_length=16, unique=True, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=16, verbose_name='课程名称')),
                ('is_attendance', models.BooleanField(default=False, verbose_name='是否走班考勤')),
                ('day_of_week', models.IntegerField(default=1, verbose_name='周')),
                ('index_of_day', models.IntegerField(default=1, verbose_name='节')),
                ('start', models.TimeField(verbose_name='开始时间')),
                ('end', models.TimeField(verbose_name='结束时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='LessonAttendanceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_lesson_history_id', models.CharField(default=common.utils.get_unique_id, max_length=16, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='课程名称')),
                ('day_of_week', models.IntegerField(default=1, verbose_name='周')),
                ('index_of_day', models.IntegerField(default=1, verbose_name='节')),
                ('start', models.TimeField(verbose_name='开始时间')),
                ('end', models.TimeField(verbose_name='结束时间')),
                ('date', models.DateField(verbose_name='走班日期')),
                ('should_attendance_count', models.IntegerField(verbose_name='应到人数')),
            ],
            options={
                'verbose_name': '走班课程',
                'verbose_name_plural': '走班课程',
            },
        ),
        migrations.CreateModel(
            name='LessonAttendanceStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_time', models.DateTimeField(blank=True, null=True, verbose_name='打卡时间')),
            ],
            options={
                'verbose_name': '走班考勤',
                'verbose_name_plural': '走班考勤',
            },
        ),
        migrations.CreateModel(
            name='SchoolNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(default=common.utils.get_unique_id, max_length=16, unique=True, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='新闻标题')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片')),
                ('content', models.TextField(verbose_name='新闻内容')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
            },
        ),
        migrations.CreateModel(
            name='StudentLessonRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '学生课程关系',
                'verbose_name_plural': '学生课程关系',
            },
        ),
        migrations.CreateModel(
            name='TeacherExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_info_id', models.CharField(default=common.utils.get_unique_id, max_length=16, unique=True, verbose_name='ID')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('teacher_roles', models.CharField(default='', max_length=16, verbose_name='角色')),
                ('work_years', models.IntegerField(default=0, verbose_name='从教工龄')),
                ('graduate_school', models.CharField(max_length=32, verbose_name='毕业院校')),
                ('achievement', models.TextField(blank=True, max_length=256, null=True, verbose_name='主要成就')),
                ('introduce', models.TextField(verbose_name='自我介绍')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
            },
        ),
    ]
