# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-09 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('electronicboard', '0002_teacherextrainfo_clazz'),
        ('user', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherextrainfo',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra_info', to='user.Teacher', verbose_name='老师'),
        ),
        migrations.AddField(
            model_name='studentlessonrel',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronicboard.Lesson', verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='studentlessonrel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='schoolnews',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newses', to='school.School', verbose_name='学校'),
        ),
        migrations.AddField(
            model_name='schoolnews',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Teacher', verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='lessonattendancestudent',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='electronicboard.LessonAttendanceHistory', verbose_name='课程历史'),
        ),
        migrations.AddField(
            model_name='lessonattendancestudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='lessonattendancehistory',
            name='clazz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Class', verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='lessonattendancehistory',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='electronicboard.Lesson', verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='lessonattendancehistory',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Teacher', verbose_name='任课老师'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='clazz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Class', verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='students',
            field=models.ManyToManyField(through='electronicboard.StudentLessonRel', to='user.Student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Teacher', verbose_name='任课老师'),
        ),
        migrations.AddField(
            model_name='honorimageitem',
            name='honor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='electronicboard.ClassHonor', verbose_name='荣誉'),
        ),
        migrations.AddField(
            model_name='galleryimageitem',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='electronicboard.ClassGallery', verbose_name='相册'),
        ),
        migrations.AddField(
            model_name='classnotification',
            name='clazz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Class', verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='classnotification',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School', verbose_name='学校'),
        ),
        migrations.AddField(
            model_name='classnotification',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Teacher', verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='classhonor',
            name='clazz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Class', verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='classhonor',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Teacher', verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='classgallery',
            name='clazz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Class', verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='classgallery',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Teacher', verbose_name='上传者'),
        ),
    ]
